const retailers = [
  {
    id: 1,
    name: "Amit Sharma",
    storeName: "Sharma Medicals",
    email: "amit.sharma@example.com",
    contact: "+91 9876543210",
    location: "Kolkata, India",
    rating: 4.6,
    yearsInBusiness: 8,
    orders: [
      {
        orderId: "ORD1001",
        customerName: "Jane Doe",
        date: "2024-09-01",
        status: "Shipped",
        total: 125.5,
        medicineName: "Paracetamol 500mg",
        quantity: 30,
      },
      {
        orderId: "ORD1002",
        customerName: "John Smith",
        date: "2024-08-30",
        status: "Delivered",
        total: 300.0,
        medicineName: "Aspirin 75mg",
        quantity: 50,
      },
      {
        orderId: "ORD1003",
        customerName: "Emily White",
        date: "2024-08-28",
        status: "Pending",
        total: 45.75,
        medicineName: "Ibuprofen 200mg",
        quantity: 15,
      },
    ],
    feedback: [
      {
        id: 1,
        customerName: "Michael Brown",
        date: "2024-09-02",
        rating: 5,
        comment:
          "Excellent service and fast delivery! The products were exactly as described.",
      },
      {
        id: 2,
        customerName: "Jessica Lee",
        date: "2024-09-01",
        rating: 4,
        comment:
          "Good experience overall. The product quality is great, but delivery was a day late.",
      },
    ],
  },
  {
    id: 2,
    name: "Neha Traders",
    storeName: "Neha Medicines",
    email: "neha.traders@example.com",
    contact: "+91 9876500000",
    location: "Delhi, India",
    rating: 4.8,
    yearsInBusiness: 10,
    orders: [
      {
        orderId: "ORD2001",
        customerName: "Rahul Verma",
        date: "2024-09-03",
        status: "Delivered",
        total: 550.0,
        medicineName: "Metformin 500mg",
        quantity: 100,
      },
       {
        orderId: "ORD2002",
        customerName: "Priya Sharma",
        date: "2024-09-04",
        status: "Shipped",
        total: 180.0,
        medicineName: "Atorvastatin 10mg",
        quantity: 30,
      },
    ],
    feedback: [
      {
        id: 1,
        customerName: "Anita Kumar",
        date: "2024-09-02",
        rating: 5,
        comment: "Highly professional. Will buy again.",
      },
    ],
  },
  {
    id: 3,
    name: "HealthPlus Store",
    storeName: "HealthPlus Pharmacy",
    email: "healthplus@example.com",
    contact: "+91 9988776655",
    location: "Mumbai, India",
    rating: 4.3,
    yearsInBusiness: 5,
    orders: [
      {
        orderId: "ORD3001",
        customerName: "Suresh Das",
        date: "2024-09-04",
        status: "Pending",
        total: 99.99,
        medicineName: "Amoxicillin 250mg",
        quantity: 20,
      },
      {
        orderId: "ORD3002",
        customerName: "Priya Sen",
        date: "2024-09-01",
        status: "Shipped",
        total: 210.5,
        medicineName: "Omeprazole 20mg",
        quantity: 45,
      },
    ],
    feedback: [
      {
        id: 1,
        customerName: "Vikram Singh",
        date: "2024-09-03",
        rating: 4,
        comment: "Good service but delivery charges are high.",
      },
    ],
  },
];

export default retailers;
